### ISSUE TITLE
Ambiguous reference to member 'node'

### ISSUE THREAD

**Issue by tgdn** [MaxDesiatov/Tokamak#68]
Copied the example from the README using macOs TokamakAppKit (version 0.1).
macOS 10.14
Xcode 10.1

![image](https://user-images.githubusercontent.com/480050/54529374-06309700-4980-11e9-812d-9ab0c321e76d.png)

**Comment by MaxDesiatov** [comment]
Hi @tgdn! Thank you so much for reporting this and I'm so sorry for the example snippet in README not having working code. I will update it right away. Here's the version that should work:

```swift
struct Counter: LeafComponent {
  struct Props: Equatable {
    let countFrom: Int
  }

  static func render(props: Props, hooks: Hooks) -> AnyNode {
    let count = hooks.state(props.countFrom)

    return StackView.node(.init(
      Edges.equal(to: .parent),
      axis: .vertical,
      distribution: .fillEqually), [
        Button.node(Button.Props(
          onPress: Handler { count.set { $0 + 1 } },
          text: "Increment"
        )),
        Label.node(.init(alignment: .center, text: "\(count.value)"))
    ])
  }
}
```

Please bear in mind that macOS renderer supports only a few basic components, but I'm currently working on adding support for more components in the next version. Also, you'll need to create a view controller that renders your component:

```swift
import TokamakAppKit

final class ViewController: TokamakViewController {
  override var node: AnyNode {
    return View.node(
      .init(Style([
        Edges.equal(to: .parent),
        Width.equal(to: 200),
        Height.equal(to: 100),
      ])),
      Counter.node(.init(countFrom: 1))
    )
  }
}
```

The best way to try Tokamak on both iOS and macOS is to clone the repository and run `pod install` in the `Example` directory, which contains sample code for both platforms.

**Comment by MaxDesiatov** [comment]
I've just added [detailed steps for running the Example project](https://github.com/MaxDesiatov/Tokamak#example-project) to README, please feel free to reopen the issue and report any other problems. Thanks again!

**Comment by tgdn** [comment]
Thanks for the quick reply. That fixed the issue.
