### ISSUE TITLE
Add Tokamak project linter

### ISSUE THREAD

**Issue by hodovani** [MaxDesiatov/Tokamak#77]
Create command-line util to lint projects that use Tokamak.

Todo:
- [x] Add `Linter.md` for linter documentation
- [x] Verify that SwiftSyntax 0.5 is able to parse the Example project
- [x] Add lint error `Props is not Equatable`
- [x] Add unit-tests to lint functions
- [x] Add `lintFile -> [LintError]`
- [x] Make `lintFolder` use `lintFile`
- [x] Make error output more user readable
- [x] Fix `TokamakLint` types access scope: remove `public` from `TokenVisitor`, `Rule`, `Reporter`, `PropsIsEquatableRule`
- [x] Fix `TokenVisitor` handling of `Range`, start and end are always equal to each other:
```swift
    node.range.startRow = row
    node.range.startColumn = column
    node.range.endRow = row
    node.range.endColumn = column
```
- [x] Fix `processToken`, `kind` variable is unused:
```swift
  private func processToken(_ token: TokenSyntax) {
    var kind = "\(token.tokenKind)"
    if let index = kind.firstIndex(of: "(") {
      kind = String(kind.prefix(upTo: index))
    }
    if kind.hasSuffix("Keyword") {
      kind = "keyword"
    }

    column += token.text.count
  }
```
- [x] Fix `walkAndGrab`, make it `private`, remove `if node.children.count > 0` condition
- [x] Investigate if [`SwiftCLI`](https://github.com/jakeheis/SwiftCLI) package can be used in `TokamakCLI` module
- [x] Rename `TokamakCLI` to `tokamak` in Package.swift for Swift 5.0 and 4.2
```swift
.executable(name: "tokamak", targets: ["TokamakCLI"])
```
- [x] Lint "Only one render in component"
- [x] One render function rule should check all components, not only hooked components.
- [X] Lint "Rules of Hooks"
- [X] Lint "Components can only be declared as structs"
- [x] Integrate [`swift-log`](https://github.com/apple/swift-log) package
- [x] Remove direct usage of `print`, implement configurable output for stdout or files with a custom `LogHandler` implementation for `swift-log`

Long-term:
- [ ] Lint "Arguments order"
- [ ] Lint "Unused argument: hooks, children"
- [ ] Lint "Declare non-static properties and functions in component"
- [ ] Lint Rules of Hooks within extensions for all Hooks, not just `state`

**Comment by MaxDesiatov** [comment]
Closing as outdated
